name: assignment3
on:
    push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Build the Docker Image
          run: |
          docker build . --file Dockerfile.setport --tag \
          ${{ secrets.DOCKER_COURSE_USERNAME }}/assignment3dockfile